config/routes.rb
Rails.application.routes.draw do
  resources :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  include HTTParty

  # def initialize(start_date, end_date, first_name, last_name, clothes_balance, active, status, member_type, referred_by, boost_credit, birthday_boost, cost, email, add_on, flagged_member)
  #   @start_date  = start_date
  #   @end_date = end_date
  #   @first_name = first_name
  #   @last_name = last_name
  #   @clothes_balance = clothes_balance
  #   @active = active
  #   @status = status
  #   @member_type = member_type
  #   @referred_by = referred_by
  #   @boost_credit = boost_credit
  #   @birthday_boost = birthday_boost
  #   @cost = cost
  #   @email = email
  #   @add_on = add_on
  #   @flagged_member = flagged_member
  # end



  def self.response
    auth = {
      username: "...",
      password: "..."
    }

    options = {
      # basic_auth: auth,
      # headers: { "X-API-KEY" => "api-key-here" }
    }

    data_url = "https://shwop-api.herokuapp.com/members"

    HTTParty.get(data_url, options)


  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = JSON.parse(Member.response.to_s)

    puts '******************************************************'
    puts @members

    @members.each do |member|
      @member = Member.new(member)
      puts @member
    end


    # puts @members

  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:start_date, :end_date, :first_name, :last_name, :clothes_balance, :active, :status, :member_type, :referred_by, :boost_credit, :birthday_boost, :cost, :email, :add_on, :flagged_member)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShwopAdmin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date, id: :member_start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date, id: :member_end_date %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :member_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :member_last_name %>
  </div>

  <div class="field">
    <%= form.label :clothes_balance %>
    <%= form.number_field :clothes_balance, id: :member_clothes_balance %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.number_field :active, id: :member_active %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status, id: :member_status %>
  </div>

  <div class="field">
    <%= form.label :member_type %>
    <%= form.text_field :member_type, id: :member_member_type %>
  </div>

  <div class="field">
    <%= form.label :referred_by %>
    <%= form.text_field :referred_by, id: :member_referred_by %>
  </div>

  <div class="field">
    <%= form.label :boost_credit %>
    <%= form.text_field :boost_credit, id: :member_boost_credit %>
  </div>

  <div class="field">
    <%= form.label :birthday_boost %>
    <%= form.check_box :birthday_boost, id: :member_birthday_boost %>
  </div>

  <div class="field">
    <%= form.label :cost %>
    <%= form.text_field :cost, id: :member_cost %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :member_email %>
  </div>

  <div class="field">
    <%= form.label :add_on %>
    <%= form.text_field :add_on, id: :member_add_on %>
  </div>

  <div class="field">
    <%= form.label :flagged_member %>
    <%= form.text_field :flagged_member, id: :member_flagged_member %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th>Start date</th>
      <th>End date</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Clothes balance</th>
      <th>Active</th>
      <th>Status</th>
      <th>Member type</th>
      <th>Referred by</th>
      <th>Boost credit</th>
      <th>Birthday boost</th>
      <th>Cost</th>
      <th>Email</th>
      <th>Add On</th>
      <th>Flagged Member</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member["start_date"] %></td>
        <td><%= member["end_date"] %></td>
        <td><%= member["first_name"] %></td>
        <td><%= member["last_name"] %></td>
        <td><%= member["clothes_balance"] %></td>
        <td><%= member["active"] %></td>
        <td><%= member["status"] %></td>
        <td><%= member["member_type"] %></td>
        <td><%= member["referred_by"] %></td>
        <td><%= member["boost_credit"] %></td>
        <td><%= member["birthday_boost"] %></td>
        <td><%= member["cost"] %></td>
        <td><%= member["email"] %></td>
        <td><%= member["add_on"] %></td>
        <td><%= member["flagged_member"] %></td>
      
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @member.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @member.end_date %>
</p>

<p>
  <strong>First name:</strong>
  <%= @member.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @member.last_name %>
</p>

<p>
  <strong>Clothes balance:</strong>
  <%= @member.clothes_balance %>
</p>

<p>
  <strong>Active:</strong>
  <%= @member.active %>
</p>

<p>
  <strong>Status:</strong>
  <%= @member.status %>
</p>

<p>
  <strong>Member type:</strong>
  <%= @member.member_type %>
</p>

<p>
  <strong>Referred by:</strong>
  <%= @member.referred_by %>
</p>

<p>
  <strong>Boost credit:</strong>
  <%= @member.boost_credit %>
</p>

<p>
  <strong>Birthday boost:</strong>
  <%= @member.birthday_boost %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @member.cost %>
</p>

<p>
  <strong>Email:</strong>
  <%= @member.email %>
</p>

<p>
  <strong>Add On:</strong>
  <%= @member.add_on %>
</p>

<p>
  <strong>Flagged Member:</strong>
  <%= @member.flagged_member %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>